[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"
